name: Packer Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  branch:
    name: Get branch name
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Branch check
        id: branch-check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "::set-output name=env_name::production"
          else
             echo "::set-output name=env_name::sandbox"
          fi
  packer:
    name: Packer Build
    needs: [branch]
    runs-on: ubuntu-latest
    environment: ${{ needs.branch.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.6'

      - name: Packer Init
        run: |
          packer init packer

      - name: Build Image
        run: |
          packer build packer