name: Copy forked branch from PR

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: The number of PR that contain the branch you want to copy
        required: true
      gh-pat:
        description: Github PAT for use when there is a workflow update in the source branch
        required: false

env:
  API_URL: ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ inputs.pr-number }}
  GH_PAT: ${{ inputs.gh-pat || secrets.GITHUB_TOKEN }}

jobs:
  copy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ inputs.gh-pat || secrets.GITHUB_TOKEN }}
        
      - id: get-pr
        name: Get Pull Request
          # https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request
        run: |
          PR=$(curl -s -H "Accept: application/vnd.github+json" "${{ env.API_URL }}")
          echo "source-repo=$(echo "${PR}" | jq -r '.head.repo.full_name')" >> $GITHUB_OUTPUT
          echo "source-br=$(echo "${PR}" | jq -r '.head.ref')" >> $GITHUB_OUTPUT
          echo "contributor=$(echo "${PR}" | jq -r '.head.user.login')" >> $GITHUB_OUTPUT

      - name: Checkout source repository
        run: |
          git remote add contributor https://${{ github.actor }}:${GH_PAT}@github.com/${{ steps.get-pr.outputs.source-repo }}.git
          git fetch contributor
          git reset --hard contributor/${{ steps.get-pr.outputs.source-br }}

      - id: create-new-branch
        name: Create new branch
        run: |
          NEW_BR="forks/${{ steps.get-pr.outputs.contributor }}/${{ steps.get-pr.outputs.source-br }}"
          git checkout -b ${NEW_BR}
          echo "new-branch=${NEW_BR}" >> $GITHUB_OUTPUT

      - name: Push new branch
        run: |
          git push -f --set-upstream origin ${{ steps.create-new-branch.outputs.new-branch }}

